<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelas_siswa extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kelas_siswa_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'kelas_siswa/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'kelas_siswa/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'kelas_siswa/index.html';
            $config['first_url'] = base_url() . 'kelas_siswa/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Kelas_siswa_model->total_rows($q);
        $kelas_siswa = $this->Kelas_siswa_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'kelas_siswa_data' => $kelas_siswa,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('kelas_siswa/kelas_siswa_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Kelas_siswa_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'kd_siswa' => $row->kd_siswa,
	    );
            $this->load->view('kelas_siswa/kelas_siswa_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelas_siswa'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kelas_siswa/create_action'),
	    'id' => set_value('id'),
	    'kd_siswa' => set_value('kd_siswa'),
	);
        $this->load->view('kelas_siswa/kelas_siswa_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'kd_siswa' => $this->input->post('kd_siswa',TRUE),
	    );

            $this->Kelas_siswa_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kelas_siswa'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kelas_siswa_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kelas_siswa/update_action'),
		'id' => set_value('id', $row->id),
		'kd_siswa' => set_value('kd_siswa', $row->kd_siswa),
	    );
            $this->load->view('kelas_siswa/kelas_siswa_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelas_siswa'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'kd_siswa' => $this->input->post('kd_siswa',TRUE),
	    );

            $this->Kelas_siswa_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kelas_siswa'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kelas_siswa_model->get_by_id($id);

        if ($row) {
            $this->Kelas_siswa_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kelas_siswa'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelas_siswa'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kd_siswa', 'kd siswa', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kelas_siswa.php */
/* Location: ./application/controllers/Kelas_siswa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-18 16:47:41 */
/* http://harviacode.com */